### ISSUE TITLE
Avaliar o modelo de upload de arquivos

### ISSUE THREAD

**Issue by AtilaAssuncao** [CofferHub/nodejs-mvc-boilerplate#24]

**Comment by AtilaAssuncao** [comment]
@Dheyson , @augustolimads , @Jose-Claudivan , Qual a opinião de vocês em adicionar upload de arquivos em um template?

**Comment by Dheyson** [comment]
@AtilaAssuncao Acho que não tem problema. Usuário ter uma imagem e um adicional, boa parte não tem implementação para arquivos.
Detalhe e onde e como salvar.

**Comment by AtilaAssuncao** [comment]
> @AtilaAssuncao Acho que não tem problema. Usuário ter uma imagem e um adicional, boa parte não tem implementação para arquivos.
> Detalhe e onde e como salvar.

Certo, local pro ambiente de desenvolvimento e no ambiente de produção vai precisar discutir
